name: pg-extension-tests

on:
  push:
  pull_request:

jobs:
  pg-extension-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build docker image
        run: ./scripts/docker-ci-build-image.sh
      - name: PGRX tests (pg_debyte_ext)
        run: ./scripts/docker-ci-test-pg-extension.sh
      - name: Workspace tests (include pg_debyte_pgrx)
        run: docker run --rm -t pg-debyte-ci bash -lc "\
            cargo test --workspace --exclude pg_debyte_ext \
          "
